From: newmail@new.com
To: newmail@new.com
Subject: dadadkajdkjalkdjakdjklajdlkad
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw=="

--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

report meeting, hello i have a cuaduaud

--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Disposition: attachment; filename="main.py"
Content-Transfer-Encoding: base64

ZnJvbSBQeVF0Ni5RdFdpZGdldHMgaW1wb3J0IFFBcHBsaWNhdGlvbiwgUU1haW5XaW5kb3cNCmZyb20gUHlRdDYgaW1wb3J0IHVpYw0KaW1wb3J0IG5ld19tYWlsDQoNCmNsYXNzIE1haW4oUU1haW5XaW5kb3cpOg0KICAgIGRlZiBfX2luaXRfXyhzZWxmKToNCiAgICAgICAgc3VwZXIoKS5fX2luaXRfXygpDQogICAgICAgIHNlbGYuc2VuZF93aW5kb3dzID0gTm9uZQ0KICAgICAgICB1aWMubG9hZFVpKCdtYWluLnVpJywgc2VsZikNCiAgICAgICAgc2VsZi5uZXdtYWlsLmNsaWNrZWQuY29ubmVjdChzZWxmLnNlbmRfbmV3X21haWwpDQoNCg0KICAgIGRlZiBzZW5kX25ld19tYWlsKHNlbGYpOg0KICAgICAgICBzZWxmLnNlbmRfd2luZG93cyA9IG5ld19tYWlsLk5ld01haWwoKQ0KICAgICAgICBzZWxmLnNlbmRfd2luZG93cy5leGVjKCkNCg0KDQo=
--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==--