From: newmail@new.com
To: newmail@new.com
Subject: test client mail load new mail
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw=="

--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

this is a test

--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Disposition: attachment; filename="bookmark.svg"
Content-Transfer-Encoding: base64

PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGlkPSJGaWxsZWQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiPjxwYXRoIGQ9Ik0yLjg0OSwyMy41NWEyLjk1NCwyLjk1NCwwLDAsMCwzLjI2Ni0uNjQ0TDEyLDE3LjA1M2w1Ljg4NSw1Ljg1M2EyLjk1NiwyLjk1NiwwLDAsMCwyLjEuODgxLDMuMDUsMy4wNSwwLDAsMCwxLjE3LS4yMzdBMi45NTMsMi45NTMsMCwwLDAsMjMsMjAuNzc5VjVhNS4wMDYsNS4wMDYsMCwwLDAtNS01SDZBNS4wMDYsNS4wMDYsMCwwLDAsMSw1VjIwLjc3OUEyLjk1MywyLjk1MywwLDAsMCwyLjg0OSwyMy41NVoiLz48L3N2Zz4K
--dGhpc19pc190aGVfc2VwYXJhdGVkX3N0cmluZw==--